name: Update ICS Calendar

on:
  schedule:
    - cron: "*/30 * * * *"   # every 30 minutes
  workflow_dispatch:          # manual trigger

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download ICS
        run: |
          curl -L "https://arnoldhoogerwerf.github.io/work-calendar/calendar.ics" -o calendar.ics
      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add calendar.ics
          git commit -m "Update calendar" || echo "No changes"
          git push
