name: Update ICS Calendar

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # ensures full history for git push

      - name: Download ICS
        run: |
          ICS_URL="https://arnoldhoogerwerf.github.io/work-calendar/calendar.ics"
          curl -L "$ICS_URL" -o calendar.ics
          echo "ICS downloaded"

      - name: Commit and push using PAT
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add calendar.ics
          git diff --cached --quiet || git commit -m "Update calendar"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/arnoldhoogerwerf/work-calendar.git
